# Service configuration
service_name: "voice_bot"

# Telegram Bot Token
bot_token: "YOUR_BOT_TOKEN_HERE"

# List of Telegram usernames that are allowed to use /insert and /download commands
authorized_users:
  - AigizK
  - chemyshev

# Default language for messages
default_language: "ba"

notifications:
  enabled: true
  interval_hours: 24  # Set to 0 to disable
