# Service configuration
service_name: "voice_bot"

# Telegram Bot Token
bot_token: "7733878403:AAHfsoS7B7xYvepX-NYiIIQsyWTPYfZ3JuA"

# List of Telegram usernames that are allowed to use /insert and /download commands
authorized_users:
  - atabekm
  - davron112
  - quyashbek

# Default language for messages
default_language: "kar"

notifications:
  enabled: true
  interval_hours: 24  # Set to 0 to disable
