# List of Telegram usernames that are allowed to use /insert and /download commands
authorized_users:
  - AigizK
  - chemyshev

notifications:
  enabled: true
  interval_hours: 24  # Set to 0 to disable
